export const CREATE_TODO = "create_todo"
export const FETCH_TODOS = "fetch_todos"
export const FETCH_TODO = "fetch_todo"
export const UPDATE_TODO = "update_todo"
export const UPDATE_PRIORITY = "update_priority"
export const DELETE_TODO = "update_priority"